fix(rabbitmq): prevent unhandled promise rejection warning
golevelup/nestjs pull request #260
Opened 2021-05-11 15:33 UTC by arjenvdhave

Catch and rethrow errors from the publish function to prevent UnhandledPromiseRejectionWarning

fix #259

2021-05-17 15:28 UTC, WonderPanda requested changes

2021-05-17 15:28 UTC, WonderPanda commented on packages/rabbitmq/src/amqp/connection.ts
> +      throw e;
@arjenvdhave This isn't the error, its an import for `express`.

2021-05-17 15:33 UTC, arjenvdhave commented on packages/rabbitmq/src/amqp/connection.ts
> +      throw e;
ah damn, sorry my vscode made this weird import

2021-05-18 14:12 UTC, WonderPanda commented
@arjenvdhave Looking at this some more, I don't think we actually need the try/catch here. All that is required for the error to bubble up properly is the `await` in front of `this.publish` so that the promise isn't treated in a fire and forget manner.

2021-05-18 14:36 UTC, arjenvdhave commented
Yes the try catch seems unnecessary indeed, will remove it

2021-05-18 14:54 UTC, WonderPanda approved these changes

2021-05-18 14:56 UTC, merged