feat(rabbitmq): add the option to avoid declaring exchanges
golevelup/nestjs pull request #506
Opened 2022-09-23 21:47 UTC by frankmangone

It is entirely possible for a rabbitmq user to not have rights to declare an exchange, and just consume it instead. This is the motivation of this PR: I couldn't find any option in the current state of the package that allows me to do this (only patching!).

Implementation is fairly simple: if I set the exchange creation flag to `false`, I should only check for its existence.

This is crucial for the project I'm working on, so I'd really appreciate if this is added as a feature. If it's not, I can always continue to patch, but this needs to happen on my side :)

2022-09-23 23:06 UTC, underfisk requested changes
LGTM, i would ask for some test coverage 🙏

2022-09-24 11:43 UTC, frankmangone commented
> LGTM, i would ask for some test coverage 🙏

Will see what I can do about that!

2022-09-25 18:51 UTC, frankmangone commented
@underfisk Added the requested tests, mind checking if that works for you? Looking good on my end :)

2022-09-26 12:59 UTC, underfisk approved these changes

2022-09-26 12:59 UTC, underfisk commented
@frankmangone Thanks for this addition, LGTM!

2022-09-26 12:59 UTC, merged