feat(rabbitmq): add consumeOption to createSubscriber()
golevelup/nestjs pull request #535
Opened 2022-12-01 08:14 UTC by m1n-q

2022-12-14 15:40 UTC, underfisk requested changes
LGTM, i have some minor requests

2022-12-14 15:40 UTC, underfisk commented on packages/rabbitmq/src/amqp/connection.ts
> +    consumeOption?: ConsumeOptions
Rename to plural `consumeOptions`

2022-12-14 15:40 UTC, underfisk commented on packages/rabbitmq/src/rabbitmq.interfaces.ts
> +export interface ConsumeOptions {
Should this extend or pick from the official library? I wonder if they do have an internal/public interface if we shouldn't use it directly. Could you investigate that?

2023-07-04 14:09 UTC, underfisk approved these changes

2023-07-04 15:32 UTC, merged

2023-08-14 13:02 UTC, m1n-q commented on packages/rabbitmq/src/rabbitmq.interfaces.ts
> +export interface ConsumeOptions {
Oh, sorry. I didn't notice the request because the project using the library was finished before your comment.